### ISSUE TITLE
GENESIS transaction type should read 7-bytes, not 4-bytes

### ISSUE THREAD

**Issue by jcramer** [simpleledger/slp-specifications#8]
A user reviewing the spec caught a typo or lack of clarity in the field that is meant to represent the minimum byte requirement for a particular field.  `transaction_type` for GENESIS transaction should be 7-bytes, not 4-bytes.

https://github.com/simpleledger/slp-specifications/blame/master/slp-token-type-1.md#L293

**Comment by markblundeberg** [comment]
whelp, I guess we should fix it then :D

**Comment by jcramer** [comment]
fixed in d88e1a9
